### ISSUE TITLE
Distance between vectors appears broken

### ISSUE THREAD

**Issue by kix-mcotton** [petiaccja/Mathter#16]
`using Vec3 = Vector<float, 3, false>;`
`auto test = Distance(Vec3(1.0f, 2.0f, 3.0f), Vec3(4.0f, 5.0f, 6.0f));`
Seems to hit the code
`return (lhs - rhs).Length();`
in VectorFunction.hpp:56 and complains that Length is not a member of Vector
Should it not be just
`Length(lhs - rhs);`?

**Comment by petiaccja** [comment]
Hi! You are correct. I have just added the fix and the associated tests to the master branch. Alternatively, you can just change that one line in your local sources. Thanks for reporting the issue!
