### ISSUE TITLE
Quaternion data layout incompatible with GLSL/GLTF

### ISSUE THREAD

**Issue by mgustavsson** [petiaccja/Mathter#27]
When sending a quaternion to a GLSL shader as a vec4, the Mathter fields (w,x,y,z) will map to (x,y,z,w) in GLSL which is unfortunate.

This is also a potential issue of bugs when importing quaternions from file formats that store quaternions in (x,y,z,w) order such as GLTF.

Would you consider changing the layout to put w last in the class layout?

**Comment by petiaccja** [comment]
Addressed in the 2.0.0 release. Now you can switch between `[s, i, j, k]` and `[i, j, k, s]` via a template parameter using `eQuaternionLayout`.

Thanks for your feedback!
